// flow-typed signature: 435bb0dbf3e3a1ad20ea8a42d27dc82a
// flow-typed version: <<STUB>>/rc-pagination_v^1.12.7/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-pagination'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-pagination' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-pagination/dist/rc-pagination' {
  declare module.exports: any;
}

declare module 'rc-pagination/dist/rc-pagination.min' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/index' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/KeyCode' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/bg_BG' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/ca_ES' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/cs_CZ' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/da_DK' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/de_DE' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/el_GR' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/en_GB' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/en_US' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/es_ES' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/et_EE' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/fa_IR' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/fi_FI' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/fr_FR' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/is_IS' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/it_IT' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/ja_JP' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/ko_KR' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/nl_BE' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/nl_NL' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/pl_PL' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/sk_SK' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/sr_RS' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/th_TH' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/vi_VN' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/locale/zh_TW' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/Options' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/Pager' {
  declare module.exports: any;
}

declare module 'rc-pagination/es/Pagination' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/index' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/KeyCode' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/bg_BG' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/ca_ES' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/cs_CZ' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/da_DK' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/de_DE' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/el_GR' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/en_GB' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/en_US' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/es_ES' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/et_EE' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/fa_IR' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/fi_FI' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/fr_FR' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/is_IS' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/it_IT' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/ja_JP' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/ko_KR' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/nl_BE' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/nl_NL' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/pl_PL' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/sk_SK' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/sr_RS' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/th_TH' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/vi_VN' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/locale/zh_TW' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/Options' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/Pager' {
  declare module.exports: any;
}

declare module 'rc-pagination/lib/Pagination' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-pagination/dist/rc-pagination.js' {
  declare module.exports: $Exports<'rc-pagination/dist/rc-pagination'>;
}
declare module 'rc-pagination/dist/rc-pagination.min.js' {
  declare module.exports: $Exports<'rc-pagination/dist/rc-pagination.min'>;
}
declare module 'rc-pagination/es/index.js' {
  declare module.exports: $Exports<'rc-pagination/es/index'>;
}
declare module 'rc-pagination/es/KeyCode.js' {
  declare module.exports: $Exports<'rc-pagination/es/KeyCode'>;
}
declare module 'rc-pagination/es/locale/bg_BG.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/bg_BG'>;
}
declare module 'rc-pagination/es/locale/ca_ES.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/ca_ES'>;
}
declare module 'rc-pagination/es/locale/cs_CZ.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/cs_CZ'>;
}
declare module 'rc-pagination/es/locale/da_DK.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/da_DK'>;
}
declare module 'rc-pagination/es/locale/de_DE.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/de_DE'>;
}
declare module 'rc-pagination/es/locale/el_GR.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/el_GR'>;
}
declare module 'rc-pagination/es/locale/en_GB.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/en_GB'>;
}
declare module 'rc-pagination/es/locale/en_US.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/en_US'>;
}
declare module 'rc-pagination/es/locale/es_ES.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/es_ES'>;
}
declare module 'rc-pagination/es/locale/et_EE.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/et_EE'>;
}
declare module 'rc-pagination/es/locale/fa_IR.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/fa_IR'>;
}
declare module 'rc-pagination/es/locale/fi_FI.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/fi_FI'>;
}
declare module 'rc-pagination/es/locale/fr_BE.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/fr_BE'>;
}
declare module 'rc-pagination/es/locale/fr_FR.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/fr_FR'>;
}
declare module 'rc-pagination/es/locale/is_IS.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/is_IS'>;
}
declare module 'rc-pagination/es/locale/it_IT.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/it_IT'>;
}
declare module 'rc-pagination/es/locale/ja_JP.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/ja_JP'>;
}
declare module 'rc-pagination/es/locale/ko_KR.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/ko_KR'>;
}
declare module 'rc-pagination/es/locale/nb_NO.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/nb_NO'>;
}
declare module 'rc-pagination/es/locale/nl_BE.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/nl_BE'>;
}
declare module 'rc-pagination/es/locale/nl_NL.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/nl_NL'>;
}
declare module 'rc-pagination/es/locale/pl_PL.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/pl_PL'>;
}
declare module 'rc-pagination/es/locale/pt_BR.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/pt_BR'>;
}
declare module 'rc-pagination/es/locale/ru_RU.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/ru_RU'>;
}
declare module 'rc-pagination/es/locale/sk_SK.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/sk_SK'>;
}
declare module 'rc-pagination/es/locale/sr_RS.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/sr_RS'>;
}
declare module 'rc-pagination/es/locale/sv_SE.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/sv_SE'>;
}
declare module 'rc-pagination/es/locale/th_TH.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/th_TH'>;
}
declare module 'rc-pagination/es/locale/vi_VN.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/vi_VN'>;
}
declare module 'rc-pagination/es/locale/zh_CN.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/zh_CN'>;
}
declare module 'rc-pagination/es/locale/zh_TW.js' {
  declare module.exports: $Exports<'rc-pagination/es/locale/zh_TW'>;
}
declare module 'rc-pagination/es/Options.js' {
  declare module.exports: $Exports<'rc-pagination/es/Options'>;
}
declare module 'rc-pagination/es/Pager.js' {
  declare module.exports: $Exports<'rc-pagination/es/Pager'>;
}
declare module 'rc-pagination/es/Pagination.js' {
  declare module.exports: $Exports<'rc-pagination/es/Pagination'>;
}
declare module 'rc-pagination/lib/index.js' {
  declare module.exports: $Exports<'rc-pagination/lib/index'>;
}
declare module 'rc-pagination/lib/KeyCode.js' {
  declare module.exports: $Exports<'rc-pagination/lib/KeyCode'>;
}
declare module 'rc-pagination/lib/locale/bg_BG.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/bg_BG'>;
}
declare module 'rc-pagination/lib/locale/ca_ES.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/ca_ES'>;
}
declare module 'rc-pagination/lib/locale/cs_CZ.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/cs_CZ'>;
}
declare module 'rc-pagination/lib/locale/da_DK.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/da_DK'>;
}
declare module 'rc-pagination/lib/locale/de_DE.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/de_DE'>;
}
declare module 'rc-pagination/lib/locale/el_GR.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/el_GR'>;
}
declare module 'rc-pagination/lib/locale/en_GB.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/en_GB'>;
}
declare module 'rc-pagination/lib/locale/en_US.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/en_US'>;
}
declare module 'rc-pagination/lib/locale/es_ES.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/es_ES'>;
}
declare module 'rc-pagination/lib/locale/et_EE.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/et_EE'>;
}
declare module 'rc-pagination/lib/locale/fa_IR.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/fa_IR'>;
}
declare module 'rc-pagination/lib/locale/fi_FI.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/fi_FI'>;
}
declare module 'rc-pagination/lib/locale/fr_BE.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/fr_BE'>;
}
declare module 'rc-pagination/lib/locale/fr_FR.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/fr_FR'>;
}
declare module 'rc-pagination/lib/locale/is_IS.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/is_IS'>;
}
declare module 'rc-pagination/lib/locale/it_IT.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/it_IT'>;
}
declare module 'rc-pagination/lib/locale/ja_JP.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/ja_JP'>;
}
declare module 'rc-pagination/lib/locale/ko_KR.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/ko_KR'>;
}
declare module 'rc-pagination/lib/locale/nb_NO.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/nb_NO'>;
}
declare module 'rc-pagination/lib/locale/nl_BE.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/nl_BE'>;
}
declare module 'rc-pagination/lib/locale/nl_NL.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/nl_NL'>;
}
declare module 'rc-pagination/lib/locale/pl_PL.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/pl_PL'>;
}
declare module 'rc-pagination/lib/locale/pt_BR.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/pt_BR'>;
}
declare module 'rc-pagination/lib/locale/ru_RU.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/ru_RU'>;
}
declare module 'rc-pagination/lib/locale/sk_SK.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/sk_SK'>;
}
declare module 'rc-pagination/lib/locale/sr_RS.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/sr_RS'>;
}
declare module 'rc-pagination/lib/locale/sv_SE.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/sv_SE'>;
}
declare module 'rc-pagination/lib/locale/th_TH.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/th_TH'>;
}
declare module 'rc-pagination/lib/locale/vi_VN.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/vi_VN'>;
}
declare module 'rc-pagination/lib/locale/zh_CN.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/zh_CN'>;
}
declare module 'rc-pagination/lib/locale/zh_TW.js' {
  declare module.exports: $Exports<'rc-pagination/lib/locale/zh_TW'>;
}
declare module 'rc-pagination/lib/Options.js' {
  declare module.exports: $Exports<'rc-pagination/lib/Options'>;
}
declare module 'rc-pagination/lib/Pager.js' {
  declare module.exports: $Exports<'rc-pagination/lib/Pager'>;
}
declare module 'rc-pagination/lib/Pagination.js' {
  declare module.exports: $Exports<'rc-pagination/lib/Pagination'>;
}
