// @flow

export const SET_LOCALE = 'SET_LOCALE';
export const ADD_POSTLIST_DATA = 'ADD_POSTLIST_DATA';
export const ADD_POST_DATA = 'ADD_POST_DATA';
export const SET_POSTS_CATEGORY = 'SET_POSTS_CATEGORY';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST';
export const GET_RANDOM_ANIMAL = 'GET_RANDOM_ANIMAL';
